### ISSUE TITLE
Meet trouble in "Print It" on [Graz] Prebuilt packages for Mac.

### ISSUE THREAD

**Issue by shinsahara** [tomooda/ViennaTalk#9] opened 2022-05-07 04:15 UTC
After installing the "ViennaTalk-mac-x64.dmg", ran ViennaTalk.app and "Print it" 1+2 in Workspace.
Then the following window appeared.

![ViennaTalk-mac-x64_Graz](https://user-images.githubusercontent.com/8341396/167237375-ce7dc2af-b333-49d4-9d96-69a361370545.jpg)

**Comment by shinsahara** [comment] 2022-05-07 04:19
My environment is the followings:

OS: macOS 12.3.1 (21E258)
Processor: 3 GHz 10コアIntel Xeon W
Memory: 64 GB 2666 MHz DDR4

**Comment by tomooda** [comment] 2022-05-07 05:02
Thanks, it seems it's caused by the change in the virtual machine. I'll post a fix soon.

**Comment by tomooda** [comment] 2022-05-07 05:06
`FileSystem workingDirectory` used to return the image directory, but now it returns the root when Launched as a standalone app. I'll change the code to use FileLocator localDirectory / 'ViennaTalk' instead.

**Comment by tomooda** [comment] 2022-05-07 07:11
It's now fixed. https://github.com/tomooda/ViennaTalk/releases/download/graz/ViennaTalk-mac-x64.dmg
Thank you for the report!

**Closed by tomooda** 2022-05-07 07:11 UTC
Labels: bug
